use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# Api.Web.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :api, Api.Web.Endpoint,
  http: [port: 4000],
  url: [host: "neochat.backslash.fr", port: 4000],
  server: true,
  debug_errors: false,
  code_reloader: false,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :api, Api.Repo,
       adapter: Ecto.Adapters.Postgres,
       username: "postgres",
       password: "postgres",
       database: "neochat",
       hostname: "postgres",
       pool_size: 10

config :api, Api.Web.Guardian,
       issuer: "neochat",
       secret_key: "7PXewtSUeh3j1oSu53FWE5AdAcsJYu/wUVzUwDfGCnrKTPDfor8LZiQaEHmz7zda"

config :api, Api.Web.AuthPipeline,
       module: Api.Web.Guardian,
       error_handler: Api.Web.ErrorHandler